name: Build image for Release channel
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate rbuild changelog
        uses: radxa-repo/rbuild-changelog@main
        with:
          product: rock-5-itx
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: b${{ github.run_number }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: true
          files: .changelog/changelog.md
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        boards: [rock-5-itx]
        build_systems: [rbuild]
        distros: [debian, ubuntu]
        flavors: [kde, cli]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload rbuild image
        uses: radxa-repo/rbuild@main
        if: matrix.build_systems == 'rbuild' && matrix.distros != 'buster'
        with:
          board: ${{ matrix.boards }}
          distro: ${{ matrix.distros }}
          flavor: ${{ matrix.flavors }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload rbuild legacy image
        uses: radxa-repo/rbuild@main
        if: matrix.build_systems == 'rbuild' && matrix.distros == 'buster'
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.distros }}
          flavor: ${{ matrix.flavors }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
